# Generated by Django 4.2.6 on 2023-10-15 23:30

from django.db import migrations
from ..models import Restaurant

def load_restaurant_data(apps, schem_editor):
    Restaurant = apps.get_model("website", "Restaurant")

    Restaurant(name="Hamburguesas", 
               description="Las mejores hamburguesas con los mejores chefs!").save()
    Restaurant(name="Tacos",
               description="Los mejores tacos del mundo!").save()

    
    
def load_dish_data(apps, schem_editor):
    restaurants = Restaurant.objects.all()
    for restaurant in restaurants:
        print(f"Restaurant: {restaurant}")

    Dish = apps.get_model("website", "Dish")

    Dish(name="Burger", description="Gran burger", price=150,
         restaurant=restaurants[0]).save()
    Dish(name="Tacos al pastor", description="Taquitos", price=150,
         restaurant=restaurants[1]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_restaurant_data),
        # migrations.RunPython(load_dish_data)
    ]
