# Generated by Django 4.2.6 on 2023-10-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='subtotal_price',
        ),
        migrations.AlterField(
            model_name='orderdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.dish'),
        ),
    ]
