version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ../Dockerfile.prod
    command: gunicorn app.wsgi:application --conf ./gunicorn.conf.py
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
    image: "virtual-kiosks-prod:v1"
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=virtual_kiosks_dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
    image: "web-server-prod:v1"

volumes:
  postgres_data:
  static_volume:
